name: Run API Tests with Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api-tests:
    name: Run REST API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run API Tests
        run: mvn clean test

      - name: Archive Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: testOut/allure-results
